"""Strict validation of the envelope, parameters and formats of the API v1.

Applied rules (SPEC.txt specification):

* envelope exactly ``{api_version, command, parameters}`` ;
* any unknown, missing or wrong-typed field -> ``INVALID_ARGUMENT`` ;
* usernames: 3-64 ASCII characters ``[a-z0-9_-]`` after
  lowercase normalization; spaces and other characters are
  refused, never removed;
* passwords: >= 12 printable Unicode code points, never
  normalized;
* content: valid UTF-8, NFC, trimmed of leading/trailing White_Space
  characters, then 1-10,000 code points, without control characters;
* ``client_message_id``: 1-128 ASCII characters ``[A-Za-z0-9._:-]``;
* textual UUIDv4 accepted case-insensitively.
"""

from __future__ import annotations

import json
import re
import unicodedata
import uuid
from datetime import datetime, timedelta, timezone
from typing import Any

from .errors import ApiError, INVALID_ARGUMENT, UNKNOWN_COMMAND

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

API_VERSION = "v2"

USERNAME_RE = re.compile(r"^[A-Za-z0-9_-]+$")
CLIENT_MESSAGE_ID_RE = re.compile(r"^[A-Za-z0-9._:-]+$")
UUID4_RE = re.compile(r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

MIN_USERNAME_LEN = 3
MAX_USERNAME_LEN = 64
MIN_PASSWORD_LEN = 12
MIN_CONTENT_LEN = 1
MAX_CONTENT_LEN = 10_000
MIN_DESCRIPTION_LEN = 1
MAX_DESCRIPTION_LEN = 500
MIN_CLIENT_MESSAGE_ID_LEN = 1
MAX_CLIENT_MESSAGE_ID_LEN = 128
MIN_BUSINESS_REFERENCE_LEN = 1
MAX_BUSINESS_REFERENCE_LEN = 128
MIN_LIMIT = 1
MAX_LIMIT = 100
DEFAULT_LIMIT = 50

# Unicode categories allowed in a password: letters, marks,
# numbers, punctuation, symbols and space separators (spaces are
# explicitly allowed). Everything else (control, format, surrogates,
# line/paragraph separators...) is refused. ``unicodedata.category``
# returns two letters (e.g. "Ll"): we compare the major one, except
# for "Zs" (space) which is the only allowed "Z" category.
_PASSWORD_ALLOWED_MAJOR = frozenset("LMNPS")

# ---------------------------------------------------------------------------
# UTC service time
# ---------------------------------------------------------------------------


def now_utc() -> str:
    """Exact UTC timestamp in ``YYYY-MM-DDTHH:mm:ss.sssZ`` format.

    Generated by the service (never by the calling agent), with
    millisecond precision, conforming to the specification.
    """
    dt = datetime.now(timezone.utc)
    ms = dt.microsecond // 1000
    return f"{dt.strftime('%Y-%m-%dT%H:%M:%S')}.{ms:03d}Z"


def now_utc_offset(seconds: float) -> str:
    """UTC timestamp shifted by ``-seconds`` (same format as ``now_utc``).

    The fixed ``YYYY-MM-DDTHH:mm:ss.sssZ`` format makes comparisons of
    strings equivalent for chronological comparisons.
    """
    dt = datetime.now(timezone.utc) - timedelta(seconds=seconds)
    ms = dt.microsecond // 1000
    return f"{dt.strftime('%Y-%m-%dT%H:%M:%S')}.{ms:03d}Z"


def _invalid(message: str) -> ApiError:
    return ApiError(INVALID_ARGUMENT, message)


# ---------------------------------------------------------------------------
# Usernames
# ---------------------------------------------------------------------------


def normalize_username(raw: Any) -> str:
    """Validates and normalizes a username.

    Accepts ``[A-Za-z0-9_-]``, 3 to 64 characters, normalized to lowercase.
    """
    if not isinstance(raw, str):
        raise _invalid("The username must be a string")
    if not (MIN_USERNAME_LEN <= len(raw) <= MAX_USERNAME_LEN):
        raise _invalid(
            f"The username must contain between {MIN_USERNAME_LEN} and "
            f"{MAX_USERNAME_LEN} characters"
        )
    if not USERNAME_RE.fullmatch(raw):
        raise _invalid(
            "The username may only contain ASCII letters, "
            "digits, '_' and '-' (spaces are refused)"
        )
    return raw.lower()


def is_valid_username(raw: str) -> bool:
    """Checks without raising (used by filters)."""
    try:
        normalize_username(raw)
        return True
    except ApiError:
        return False


def normalize_organization_name(raw: Any) -> str:
    """Normalizes an organization name (same rules as usernames).

    Organization names and usernames share the same character
    set but form two distinct namespaces (section 3.5).
    """
    if not isinstance(raw, str):
        raise _invalid("The organization name must be a string")
    if not (MIN_USERNAME_LEN <= len(raw) <= MAX_USERNAME_LEN):
        raise _invalid(
            f"The organization name must contain between {MIN_USERNAME_LEN} and "
            f"{MAX_USERNAME_LEN} characters"
        )
    if not USERNAME_RE.fullmatch(raw):
        raise _invalid(
            "The organization name may only contain ASCII letters, "
            "digits, '_' and '-' (spaces are refused)"
        )
    return raw.lower()


# ---------------------------------------------------------------------------
# Human accounts (SPEC-WEB §5): derived naming and reservation.
# ---------------------------------------------------------------------------

#: Reserved suffix of human accounts (username derived from the organization).
HUMAN_SUFFIX = "_humain"


def human_username_for(organization_name: str) -> str:
    """Username derived from the human account of an organization.

    Normal form: ``{organization_name}_humain`` (unique because
    organization names are unique). If the derived name would exceed the
    username limit (very long organization names, historical case), a
    truncated form + short deterministic fingerprint — always unique and stable.
    """
    derived = f"{organization_name}{HUMAN_SUFFIX}"
    if len(derived) <= MAX_USERNAME_LEN:
        return derived
    import hashlib

    digest = hashlib.sha256(organization_name.encode("utf-8")).hexdigest()[:8]
    prefix_len = MAX_USERNAME_LEN - len(HUMAN_SUFFIX) - 1 - len(digest)
    return f"{organization_name[:prefix_len]}{HUMAN_SUFFIX}_{digest}"


def is_reserved_human_username(username: str) -> bool:
    """A name containing the human marker is reserved for the system.

    Covers the normal form (``*_humain``) and the long derived form
    (``*_humain_<8 hex>``). ``create_agent`` refuses it: no collision
    possible with a self-created human account.
    """
    return username.endswith(HUMAN_SUFFIX) or f"{HUMAN_SUFFIX}_" in username


def validate_bool(raw: Any) -> bool:
    """Validates a strict JSON boolean (``true`` or ``false``).

    ``None`` (optional parameter not used) returns ``False``:
    permissions and policies are opt-in (least privilege principle).
    """
    if raw is None:
        return False
    if type(raw) is not bool:
        raise _invalid("The parameter must be a JSON boolean (true or false)")
    return raw


# ---------------------------------------------------------------------------
# Passwords
# ---------------------------------------------------------------------------


def validate_password(raw: Any) -> str:
    """Validates a password: >= 12 printable Unicode characters.

    The password is never normalized: it is used exactly as
    provided.
    """
    if not isinstance(raw, str):
        raise _invalid("The password must be a string")
    if len(raw) < MIN_PASSWORD_LEN:
        raise _invalid(f"The password must contain at least {MIN_PASSWORD_LEN} characters")
    for ch in raw:
        cat = unicodedata.category(ch)
        if not (cat[0] in _PASSWORD_ALLOWED_MAJOR or cat == "Zs"):
            raise _invalid(
                "The password may only contain printable Unicode "
                "characters (control characters, line breaks and "
                "null characters are forbidden)"
            )
    return raw


# ---------------------------------------------------------------------------
# Message content
# ---------------------------------------------------------------------------


def normalize_content(raw: Any) -> str:
    """Normalizes the content of a message.

    Steps (in specification order):
    1. valid UTF-8 string (guaranteed by JSON decoding, surrogates refused);
    2. Unicode NFC normalization ;
    3. removal of leading/trailing White_Space characters;
    4. final check: 1 to 10,000 code points, no control characters.
    """
    if not isinstance(raw, str):
        raise _invalid("The message must be a string")
    _reject_surrogates(raw)
    content = unicodedata.normalize("NFC", raw)
    content = content.strip()
    length = len(content)
    if not (MIN_CONTENT_LEN <= length <= MAX_CONTENT_LEN):
        raise _invalid(
            f"The content must contain between {MIN_CONTENT_LEN} and {MAX_CONTENT_LEN} "
            "Unicode code points after normalization"
        )
    for ch in content:
        if unicodedata.category(ch) == "Cc":
            raise _invalid("The content cannot contain control characters")
    return content


def _reject_surrogates(value: str) -> None:
    """Rejects lone surrogates (not encodable in UTF-8)."""
    for ch in value:
        code = ord(ch)
        if 0xD800 <= code <= 0xDFFF:
            raise _invalid("The text contains invalid UTF-8 sequences")


def normalize_description(raw: Any) -> str:
    """Normalizes an agent description (section 3 of the specification).

    Same rules as message content, with a limit of 500 code
    points: valid UTF-8 string, NFC normalization, trimming of
    leading/trailing `White_Space` characters, 1 to 500 code points, no
    control characters.
    """
    if not isinstance(raw, str):
        raise _invalid("The description must be a string")
    _reject_surrogates(raw)
    description = unicodedata.normalize("NFC", raw)
    description = description.strip()
    length = len(description)
    if not (MIN_DESCRIPTION_LEN <= length <= MAX_DESCRIPTION_LEN):
        raise _invalid(
            f"The description must contain between {MIN_DESCRIPTION_LEN} and "
            f"{MAX_DESCRIPTION_LEN} Unicode code points after normalization"
        )
    for ch in description:
        if unicodedata.category(ch) == "Cc":
            raise _invalid("The description cannot contain control characters")
    return description


# ---------------------------------------------------------------------------
# Identifiers
# ---------------------------------------------------------------------------


def validate_client_message_id(raw: Any) -> str:
    """Validates a ``client_message_id``: 1-128 characters ``[A-Za-z0-9._:-]``."""
    if not isinstance(raw, str):
        raise _invalid("client_message_id must be a string")
    if not (MIN_CLIENT_MESSAGE_ID_LEN <= len(raw) <= MAX_CLIENT_MESSAGE_ID_LEN):
        raise _invalid(
            f"client_message_id must contain between {MIN_CLIENT_MESSAGE_ID_LEN} and "
            f"{MAX_CLIENT_MESSAGE_ID_LEN} characters"
        )
    if not CLIENT_MESSAGE_ID_RE.fullmatch(raw):
        raise _invalid(
            "client_message_id may only contain ASCII characters "
            "from a-z, A-Z, 0-9, '.', '_', ':' and '-'"
        )
    return raw


def normalize_uuid(raw: Any, field: str = "identifier") -> str:
    """Validates a textual UUIDv4 (case-insensitive), returns the lowercase form."""
    if not isinstance(raw, str):
        raise _invalid(f"{field} must be a string")
    if not UUID4_RE.fullmatch(raw):
        raise _invalid(f"{field} must be a valid UUIDv4")
    value = uuid.UUID(raw)
    if value.version != 4 or value.variant != uuid.RFC_4122:
        raise _invalid(f"{field} must be a valid UUIDv4")
    return str(value)


def normalize_business_reference(raw: Any) -> str | None:
    """Normalizes a business reference: NFC string of 1-128 code points,
    no control characters, opaque to the server.

    ``None`` (optional parameter not provided) is accepted: a message
    without a business reference stays valid.
    """
    if raw is None:
        return None
    if not isinstance(raw, str):
        raise _invalid("business_reference must be a string")
    _reject_surrogates(raw)
    ref = unicodedata.normalize("NFC", raw)
    ref = ref.strip()
    length = len(ref)
    if not (MIN_BUSINESS_REFERENCE_LEN <= length <= MAX_BUSINESS_REFERENCE_LEN):
        raise _invalid(
            f"business_reference must contain between {MIN_BUSINESS_REFERENCE_LEN} and "
            f"{MAX_BUSINESS_REFERENCE_LEN} Unicode code points after normalization"
        )
    for ch in ref:
        if unicodedata.category(ch) == "Cc":
            raise _invalid("business_reference cannot contain control characters")
    return ref


# ---------------------------------------------------------------------------
# Tasks (F5-F9) and events (F10)
# ---------------------------------------------------------------------------

MIN_TASK_TITLE_LEN = 1
MAX_TASK_TITLE_LEN = 200
MAX_TASK_DESCRIPTION_LEN = 5_000
MAX_TASK_RESULT_LEN = 10_000
MAX_DEPENDENCIES = 20
MAX_REASON_LEN = 500

TASK_STATES = frozenset(
    {"submitted", "in_progress", "completed", "failed", "canceled", "pending_approval"}
)
TASK_PRIORITIES = frozenset({"low", "normal", "high"})

_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$")


def normalize_task_title(raw: Any) -> str:
    """Task title: NFC string of 1-200 code points, no control characters."""
    return _normalize_task_text(raw, "title", MIN_TASK_TITLE_LEN, MAX_TASK_TITLE_LEN)


def normalize_task_description(raw: Any) -> str | None:
    """Task description: NFC string of 1-5000 code points or ``None``."""
    if raw is None:
        return None
    return _normalize_task_text(
        raw, "description", 1, MAX_TASK_DESCRIPTION_LEN
    )


def normalize_task_result(raw: Any) -> str | None:
    """Task result: NFC string of 1-10,000 code points or ``None``."""
    if raw is None:
        return None
    return _normalize_task_text(raw, "result", 1, MAX_TASK_RESULT_LEN)


def normalize_reason(raw: Any) -> str | None:
    """Approval rejection reason: NFC string of 1-500 code points."""
    if raw is None:
        return None
    return _normalize_task_text(raw, "reason", 1, MAX_REASON_LEN)


def _normalize_task_text(raw: Any, field: str, min_len: int, max_len: int) -> str:
    if not isinstance(raw, str):
        raise _invalid(f"{field} must be a string")
    _reject_surrogates(raw)
    text = unicodedata.normalize("NFC", raw).strip()
    if not (min_len <= len(text) <= max_len):
        raise _invalid(
            f"{field} must contain between {min_len} and {max_len} Unicode code points "
            "after normalization"
        )
    for ch in text:
        if unicodedata.category(ch) == "Cc":
            raise _invalid(f"{field} cannot contain control characters")
    return text


def validate_due_at(raw: Any) -> str | None:
    """Due date: exact UTC date ``YYYY-MM-DDTHH:mm:ss.sssZ`` or ``None``."""
    if raw is None:
        return None
    if not isinstance(raw, str):
        raise _invalid("due_at must be a string")
    if not _DATE_RE.fullmatch(raw):
        raise _invalid("due_at must be a UTC date in the format YYYY-MM-DDTHH:mm:ss.sssZ")
    return raw


def validate_task_state(raw: Any) -> str | None:
    if raw is None:
        return None
    if raw not in TASK_STATES:
        # pending_approval is a derived state (set by request_approval),
        # not settable by update_task_state: it is not listed here.
        raise _invalid(
            "state must be one of: submitted, in_progress, completed, failed, "
            "canceled"
        )
    return raw


def validate_task_priority(raw: Any) -> str:
    if raw is None:
        return "normal"
    if raw not in TASK_PRIORITIES:
        raise _invalid("priority must be one of: low, normal, high")
    return raw


def _validate_priority_filter(raw: Any) -> str | None:
    """Priority in list filter: ``None`` = no filter."""
    if raw is None:
        return None
    return validate_task_priority(raw)


def validate_depends_on(raw: Any) -> list[str] | None:
    """Dependency list: 0-20 UUIDv4 of existing tasks (checked by
    the service)."""
    if raw is None:
        return []
    if not isinstance(raw, list):
        raise _invalid("depends_on must be a list of task identifiers")
    if len(raw) > MAX_DEPENDENCIES:
        raise _invalid(f"depends_on must contain at most {MAX_DEPENDENCIES} elements")
    out: list[str] = []
    seen: set[str] = set()
    for item in raw:
        value = normalize_uuid(item, "depends_on")
        if value not in seen:
            seen.add(value)
            out.append(value)
    return out


def _validate_optional_client_id(raw: Any) -> str | None:
    """Optional idempotency identifier (``None`` accepted)."""
    if raw is None:
        return None
    return validate_client_message_id(raw)


def validate_event_types(raw: Any) -> list[str] | None:
    """Event types filter: list of 1-20 known types."""
    from .store import events as events_store

    if raw is None:
        return None
    if not isinstance(raw, list) or any(not isinstance(i, str) for i in raw):
        raise _invalid("types must be a list of strings")
    if not (1 <= len(raw) <= 20):
        raise _invalid("types must contain between 1 and 20 elements")
    unknown = [t for t in raw if t not in events_store.EVENT_TYPES]
    if unknown:
        raise _invalid(f"Unknown event type: {unknown[0]}")
    return raw


def validate_retention_days(raw: Any) -> int | None:
    """Event retention days (SPEC.txt F10): integer 1-3650."""
    value = validate_budget(raw)
    if value is None:
        raise _invalid("retention must be a positive integer")
    if value > 3650:
        raise _invalid("retention cannot exceed 3650 days")
    return value


def validate_budget(raw: Any) -> int | None:
    """Budget value: integer >= 1 or ``None`` (no limit)."""
    if raw is None:
        return None
    if isinstance(raw, bool) or not isinstance(raw, int):
        raise _invalid("the budget must be an integer")
    if raw < 1:
        raise _invalid("the budget must be a positive integer")
    return raw


def validate_positive_seconds(raw: Any) -> int:
    """Required time threshold: integer >= 1 (never ``None`` — a null threshold
    would trigger immediate escalation, an absent threshold makes no sense
    since ``enabled=false`` already disables the mechanism)."""
    if raw is None or isinstance(raw, bool) or not isinstance(raw, int):
        raise _invalid("the threshold must be a positive integer")
    if raw < 1:
        raise _invalid("the threshold must be a positive integer")
    return raw


# ---------------------------------------------------------------------------
# Organizational structure (F13/F14): departments and fixed roles
# ---------------------------------------------------------------------------

ORG_ROLES = frozenset({"manager", "employee", "rh"})
PRINCIPAL_TYPES = frozenset({"agent", "human"})


def normalize_department_name(raw: Any) -> str:
    """Department name: same rules as organization names."""
    return normalize_organization_name(raw)


def validate_org_role(raw: Any) -> str:
    """Organizational role: one of the fixed roles (manager, employee, rh)."""
    if not isinstance(raw, str) or raw not in ORG_ROLES:
        raise _invalid("role must be one of: manager, employee, rh")
    return raw


def validate_principal_type(raw: Any) -> str:
    """Principal type (SPEC.txt F19): 'agent' (default) or 'human'."""
    if raw is None:
        return "agent"
    if not isinstance(raw, str) or raw not in PRINCIPAL_TYPES:
        raise _invalid("principal_type must be 'agent' or 'human'")
    return raw


def normalize_group_name(raw: Any) -> str:
    """Group name: NFC string of 1-64 code points, no control characters."""
    value = _normalize_card_text(raw, "name", 64)
    assert value is not None  # required
    return value


# ---------------------------------------------------------------------------
# Agent cards (F2) and capability search (F3)
# ---------------------------------------------------------------------------

MIN_CAPABILITIES = 1
MAX_CAPABILITIES = 50
MIN_CAPABILITY_LEN = 1
MAX_CAPABILITY_LEN = 64
MAX_CARD_TEXT_LEN = 128
MAX_CARD_LIMITS_LEN = 256


def _normalize_card_text(raw: Any, field: str, max_len: int) -> str | None:
    """Normalizes an optional card text field: NFC, bounds, no
    control characters. ``None`` if absent."""
    if raw is None:
        return None
    if not isinstance(raw, str):
        raise _invalid(f"{field} must be a string")
    _reject_surrogates(raw)
    text = unicodedata.normalize("NFC", raw).strip()
    if not (1 <= len(text) <= max_len):
        raise _invalid(
            f"{field} must contain between 1 and {max_len} Unicode code points after "
            "normalization"
        )
    for ch in text:
        if unicodedata.category(ch) == "Cc":
            raise _invalid(f"{field} cannot contain control characters")
    return text


def normalize_capabilities(raw: Any) -> list[str] | None:
    """Normalizes a capability list: 1-50 NFC strings of 1-64, deduplicated
    case-insensitively (the first occurrence is kept).

    ``None`` is refused: ``set_agent_card`` requires at least one capability
    (a card without capability makes no sense for discovery).
    """
    if raw is None:
        raise _invalid("capabilities is required")
    if not isinstance(raw, list) or any(isinstance(i, bool) for i in raw):
        raise _invalid("capabilities must be a list of strings")
    if not (MIN_CAPABILITIES <= len(raw) <= MAX_CAPABILITIES):
        raise _invalid(
            f"capabilities must contain between {MIN_CAPABILITIES} and {MAX_CAPABILITIES} "
            "elements"
        )
    out: list[str] = []
    seen: set[str] = set()
    for item in raw:
        value = _normalize_card_text(item, "capability", MAX_CAPABILITY_LEN)
        assert value is not None
        folded = value.casefold()
        if folded not in seen:
            seen.add(folded)
            out.append(value)
    return out


def normalize_tools(raw: Any) -> list[str] | None:
    """Normalizes a tool list: 0-50 NFC strings of 1-64, deduplicated
    case-insensitively (the first occurrence is kept)."""
    if raw is None:
        return []
    if not isinstance(raw, list) or any(isinstance(i, bool) for i in raw):
        raise _invalid("tools must be a list of strings")
    if len(raw) > MAX_CAPABILITIES:
        raise _invalid(f"tools must contain at most {MAX_CAPABILITIES} elements")
    out: list[str] = []
    seen: set[str] = set()
    for item in raw:
        value = _normalize_card_text(item, "tool", MAX_CAPABILITY_LEN)
        assert value is not None
        folded = value.casefold()
        if folded not in seen:
            seen.add(folded)
            out.append(value)
    return out


def _validate_capability_filter(value: Any) -> str | None:
    if value is None:
        return None
    return _normalize_card_text(value, "capability", MAX_CAPABILITY_LEN)


def _validate_card_text_filter(value: Any, field: str) -> str | None:
    if value is None:
        return None
    return _normalize_card_text(value, field, MAX_CARD_TEXT_LEN)


# ---------------------------------------------------------------------------
# Envelope and parameters
# ---------------------------------------------------------------------------

# Command declaration: ``params`` lists the allowed fields in
# order (name, type, required, optional semantic validator).
# ``org`` indicates that the command requires the authentication of an
# organization (instead of an agent's).
CommandSpec = tuple[str, tuple, bool]  # (name, params, org) -- see build_spec

_P = str  # base JSON type


def _spec(name: str, params: tuple, org: bool = False) -> CommandSpec:
    return (name, params, org)


def _validate_status(value: Any) -> str | None:
    if value is None:
        return None
    if value not in ("read", "unread"):
        raise _invalid("status must be 'read' or 'unread'")
    return value


def _validate_sender_filter(value: Any) -> str | None:
    if value is None:
        return None
    return normalize_username(value)


def _validate_uuid_filter(value: Any) -> str | None:
    if value is None:
        return None
    return normalize_uuid(value, "conversation_id")


def _validate_limit(value: Any) -> int:
    if value is None:
        return DEFAULT_LIMIT
    if isinstance(value, bool) or not isinstance(value, int):
        raise _invalid("limit must be an integer")
    if not (MIN_LIMIT <= value <= MAX_LIMIT):
        raise _invalid(f"limit must be an integer between {MIN_LIMIT} and {MAX_LIMIT}")
    return value


def _validate_command_name(value: Any) -> str | None:
    """Validates ``command_name`` (help): exact name of a command of the API v1.

    Exact comparison, without normalization (specification, section 13): an
    unknown name raises ``UNKNOWN_COMMAND``.
    """
    if value is None:
        return None
    if value not in COMMAND_SPECS:
        raise ApiError(UNKNOWN_COMMAND, f"Unknown command: {value}")
    return value


COMMAND_SPECS: dict[str, CommandSpec] = {
    # ------------------------------------------------------------------
    # Organization commands (organization_*_auth authentication)
    # ------------------------------------------------------------------
    "create_agent": _spec(
        "create_agent",
        (
            ("username", _P, True, normalize_username),
            ("password", _P, True, validate_password),
            ("description", _P, True, normalize_description),
            ("can_see_org_agents", bool, False, validate_bool),
            ("principal_type", _P, False, validate_principal_type),
            ("organization_name_auth", _P, True, normalize_organization_name),
            ("organization_password_auth", _P, True, None),
        ),
        org=True,
    ),
    "deactivate_agent": _spec(
        "deactivate_agent",
        (
            ("username", _P, True, normalize_username),
            ("organization_name_auth", _P, True, normalize_organization_name),
            ("organization_password_auth", _P, True, None),
        ),
        org=True,
    ),
    "reactivate_agent": _spec(
        "reactivate_agent",
        (
            ("username", _P, True, normalize_username),
            ("organization_name_auth", _P, True, normalize_organization_name),
            ("organization_password_auth", _P, True, None),
        ),
        org=True,
    ),
    "change_agent_password": _spec(
        "change_agent_password",
        (
            ("username", _P, True, normalize_username),
            ("new_password", _P, True, validate_password),
            ("organization_name_auth", _P, True, normalize_organization_name),
            ("organization_password_auth", _P, True, None),
        ),
        org=True,
    ),
    "set_agent_visibility": _spec(
        "set_agent_visibility",
        (
            ("username", _P, True, normalize_username),
            ("can_see_org_agents", bool, True, validate_bool),
            ("organization_name_auth", _P, True, normalize_organization_name),
            ("organization_password_auth", _P, True, None),
        ),
        org=True,
    ),
    "get_org_agents": _spec(
        "get_org_agents",
        (
            ("organization_name_auth", _P, True, normalize_organization_name),
            ("organization_password_auth", _P, True, None),
            ("limit", int, False, _validate_limit),
            ("cursor", _P, False, None),
        ),
        org=True,
    ),
    "set_organization_policy": _spec(
        "set_organization_policy",
        (
            ("allow_incoming_external", bool, True, validate_bool),
            ("allow_outgoing_external", bool, True, validate_bool),
            ("organization_name_auth", _P, True, normalize_organization_name),
            ("organization_password_auth", _P, True, None),
        ),
        org=True,
    ),
    "get_organization_policy": _spec(
        "get_organization_policy",
        (
            ("organization_name_auth", _P, True, normalize_organization_name),
            ("organization_password_auth", _P, True, None),
        ),
        org=True,
    ),
    "change_organization_password": _spec(
        "change_organization_password",
        (
            ("new_password", _P, True, validate_password),
            ("organization_name_auth", _P, True, normalize_organization_name),
            ("organization_password_auth", _P, True, None),
        ),
        org=True,
    ),
    # ------------------------------------------------------------------
    # Agent commands (my_*_auth authentication)
    # ------------------------------------------------------------------
    "get_my_organization": _spec(
        "get_my_organization",
        (
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "get_agent_description": _spec(
        "get_agent_description",
        (
            ("username", _P, True, normalize_username),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "list_org_agents": _spec(
        "list_org_agents",
        (
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
            ("limit", int, False, _validate_limit),
            ("cursor", _P, False, None),
        ),
    ),
    "send_message": _spec(
        "send_message",
        (
            ("recipient_username", _P, True, normalize_username),
            ("message", _P, True, normalize_content),
            ("client_message_id", _P, True, validate_client_message_id),
            ("business_reference", _P, False, normalize_business_reference),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "get_messages": _spec(
        "get_messages",
        (
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
            ("status", _P, False, _validate_status),
            ("sender_username", _P, False, _validate_sender_filter),
            ("conversation_id", _P, False, _validate_uuid_filter),
            ("limit", int, False, _validate_limit),
            ("cursor", _P, False, None),
        ),
    ),
    "get_conversation": _spec(
        "get_conversation",
        (
            ("other_username", _P, True, normalize_username),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
            ("limit", int, False, _validate_limit),
            ("cursor", _P, False, None),
        ),
    ),
    "read_message": _spec(
        "read_message",
        (
            ("message_id", _P, True, lambda v: normalize_uuid(v, "message_id")),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "get_notifications": _spec(
        "get_notifications",
        (
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
            ("limit", int, False, _validate_limit),
            ("cursor", _P, False, None),
        ),
    ),
    "mark_conversation_no_reply": _spec(
        "mark_conversation_no_reply",
        (
            ("conversation_id", _P, True, lambda v: normalize_uuid(v, "conversation_id")),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "help": _spec(
        "help",
        (
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
            ("command_name", _P, False, _validate_command_name),
        ),
    ),
    # ------------------------------------------------------------------
    # Agent cards and capability search (SPEC.txt F2/F3)
    # ------------------------------------------------------------------
    "set_agent_card": _spec(
        "set_agent_card",
        (
            ("capabilities", list, True, normalize_capabilities),
            ("domain", _P, False, lambda v: _normalize_card_text(v, "domain", MAX_CARD_TEXT_LEN)),
            ("model", _P, False, lambda v: _normalize_card_text(v, "model", MAX_CARD_TEXT_LEN)),
            ("tools", list, False, normalize_tools),
            ("sla", _P, False, lambda v: _normalize_card_text(v, "sla", MAX_CARD_TEXT_LEN)),
            ("limits", _P, False, lambda v: _normalize_card_text(v, "limits", MAX_CARD_LIMITS_LEN)),
            ("estimated_cost", _P, False, lambda v: _normalize_card_text(v, "estimated_cost", MAX_CARD_TEXT_LEN)),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "get_agent_card": _spec(
        "get_agent_card",
        (
            ("username", _P, True, normalize_username),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "approve_agent_card": _spec(
        "approve_agent_card",
        (
            ("username", _P, True, normalize_username),
            ("organization_name_auth", _P, True, normalize_organization_name),
            ("organization_password_auth", _P, True, None),
        ),
        org=True,
    ),
    "find_agents": _spec(
        "find_agents",
        (
            ("capability", _P, False, _validate_capability_filter),
            ("domain", _P, False, lambda v: _validate_card_text_filter(v, "domain")),
            ("name_contains", _P, False, lambda v: _validate_card_text_filter(v, "name_contains")),
            ("limit", int, False, _validate_limit),
            ("cursor", _P, False, None),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    # ------------------------------------------------------------------
    # Tasks, work queues, approvals, events (SPEC.txt F5-F10)
    # ------------------------------------------------------------------
    "create_task": _spec(
        "create_task",
        (
            ("title", _P, True, normalize_task_title),
            ("description", _P, False, normalize_task_description),
            ("assignee_username", _P, True, normalize_username),
            ("priority", _P, False, validate_task_priority),
            ("due_at", _P, False, validate_due_at),
            ("depends_on", list, False, validate_depends_on),
            ("business_reference", _P, False, normalize_business_reference),
            ("client_task_id", _P, False, _validate_optional_client_id),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "get_task": _spec(
        "get_task",
        (
            ("task_id", _P, True, lambda v: normalize_uuid(v, "task_id")),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "list_tasks": _spec(
        "list_tasks",
        (
            ("assignee_username", _P, False, _validate_sender_filter),
            ("state", _P, False, validate_task_state),
            ("priority", _P, False, _validate_priority_filter),
            ("due_before", _P, False, validate_due_at),
            ("limit", int, False, _validate_limit),
            ("cursor", _P, False, None),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "update_task_state": _spec(
        "update_task_state",
        (
            ("task_id", _P, True, lambda v: normalize_uuid(v, "task_id")),
            ("new_state", _P, True, validate_task_state),
            ("result", _P, False, normalize_task_result),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "transfer_task": _spec(
        "transfer_task",
        (
            ("task_id", _P, True, lambda v: normalize_uuid(v, "task_id")),
            ("assignee_username", _P, True, normalize_username),
            ("note", _P, False, normalize_reason),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "request_approval": _spec(
        "request_approval",
        (
            ("task_id", _P, True, lambda v: normalize_uuid(v, "task_id")),
            ("approver_username", _P, True, normalize_username),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "approve_task": _spec(
        "approve_task",
        (
            ("task_id", _P, True, lambda v: normalize_uuid(v, "task_id")),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "reject_task": _spec(
        "reject_task",
        (
            ("task_id", _P, True, lambda v: normalize_uuid(v, "task_id")),
            ("reason", _P, False, normalize_reason),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "get_my_work": _spec(
        "get_my_work",
        (
            ("limit", int, False, _validate_limit),
            ("cursor", _P, False, None),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "get_events": _spec(
        "get_events",
        (
            ("types", list, False, validate_event_types),
            ("limit", int, False, _validate_limit),
            ("cursor", _P, False, None),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "set_escalation_policy": _spec(
        "set_escalation_policy",
        (
            ("enabled", bool, True, validate_bool),
            ("due_after_seconds", int, True, validate_positive_seconds),
            ("failed_after_seconds", int, True, validate_positive_seconds),
            ("escalate_to_username", _P, True, normalize_username),
            ("organization_name_auth", _P, True, normalize_organization_name),
            ("organization_password_auth", _P, True, None),
        ),
        org=True,
    ),
    "get_escalation_policy": _spec(
        "get_escalation_policy",
        (
            ("organization_name_auth", _P, True, normalize_organization_name),
            ("organization_password_auth", _P, True, None),
        ),
        org=True,
    ),
    "set_agent_budget": _spec(
        "set_agent_budget",
        (
            ("username", _P, True, normalize_username),
            ("max_active_tasks", int, False, validate_budget),
            ("max_messages_per_hour", int, False, validate_budget),
            ("organization_name_auth", _P, True, normalize_organization_name),
            ("organization_password_auth", _P, True, None),
        ),
        org=True,
    ),
    "set_event_retention_days": _spec(
        "set_event_retention_days",
        (
            ("days", int, True, validate_retention_days),
            ("organization_name_auth", _P, True, normalize_organization_name),
            ("organization_password_auth", _P, True, None),
        ),
        org=True,
    ),
    # ------------------------------------------------------------------
    # Organizational structure and observability (SPEC.txt F11-F14)
    # ------------------------------------------------------------------
    "create_department": _spec(
        "create_department",
        (
            ("department_name", _P, True, normalize_department_name),
            ("organization_name_auth", _P, True, normalize_organization_name),
            ("organization_password_auth", _P, True, None),
        ),
        org=True,
    ),
    "set_agent_department": _spec(
        "set_agent_department",
        (
            ("username", _P, True, normalize_username),
            ("department_name", _P, True, normalize_department_name),
            ("role", _P, True, validate_org_role),
            ("organization_name_auth", _P, True, normalize_organization_name),
            ("organization_password_auth", _P, True, None),
        ),
        org=True,
    ),
    "get_org_structure": _spec(
        "get_org_structure",
        (
            ("organization_name_auth", _P, True, normalize_organization_name),
            ("organization_password_auth", _P, True, None),
        ),
        org=True,
    ),
    "list_department_tasks": _spec(
        "list_department_tasks",
        (
            ("department_name", _P, True, normalize_department_name),
            ("limit", int, False, _validate_limit),
            ("cursor", _P, False, None),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "get_org_audit": _spec(
        "get_org_audit",
        (
            ("since", _P, False, validate_due_at),
            ("actor_username", _P, False, _validate_sender_filter),
            ("command", _P, False, None),
            ("limit", int, False, _validate_limit),
            ("cursor", _P, False, None),
            ("organization_name_auth", _P, True, normalize_organization_name),
            ("organization_password_auth", _P, True, None),
        ),
        org=True,
    ),
    "get_org_metrics": _spec(
        "get_org_metrics",
        (
            ("organization_name_auth", _P, True, normalize_organization_name),
            ("organization_password_auth", _P, True, None),
        ),
        org=True,
    ),
    "get_server_status": _spec(
        "get_server_status",
        (
            ("organization_name_auth", _P, True, normalize_organization_name),
            ("organization_password_auth", _P, True, None),
        ),
        org=True,
    ),
    # ------------------------------------------------------------------
    # Groups, reputation, delegation, human principals (SPEC.txt F15-F19)
    # ------------------------------------------------------------------
    "create_group": _spec(
        "create_group",
        (
            ("name", _P, True, normalize_group_name),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "add_group_member": _spec(
        "add_group_member",
        (
            ("group_id", _P, True, lambda v: normalize_uuid(v, "group_id")),
            ("username", _P, True, normalize_username),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "remove_group_member": _spec(
        "remove_group_member",
        (
            ("group_id", _P, True, lambda v: normalize_uuid(v, "group_id")),
            ("username", _P, True, normalize_username),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "send_group_message": _spec(
        "send_group_message",
        (
            ("group_id", _P, True, lambda v: normalize_uuid(v, "group_id")),
            ("message", _P, True, normalize_content),
            ("client_message_id", _P, False, _validate_optional_client_id),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "get_group_messages": _spec(
        "get_group_messages",
        (
            ("group_id", _P, True, lambda v: normalize_uuid(v, "group_id")),
            ("limit", int, False, _validate_limit),
            ("cursor", _P, False, None),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "get_group_members": _spec(
        "get_group_members",
        (
            ("group_id", _P, True, lambda v: normalize_uuid(v, "group_id")),
            ("limit", int, False, _validate_limit),
            ("cursor", _P, False, None),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "list_my_groups": _spec(
        "list_my_groups",
        (
            ("limit", int, False, _validate_limit),
            ("cursor", _P, False, None),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "get_agent_reputation": _spec(
        "get_agent_reputation",
        (
            ("username", _P, True, normalize_username),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "create_delegation": _spec(
        "create_delegation",
        (
            ("task_id", _P, True, lambda v: normalize_uuid(v, "task_id")),
            ("delegatee_username", _P, True, normalize_username),
            ("expires_at", _P, True, validate_due_at),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "revoke_delegation": _spec(
        "revoke_delegation",
        (
            ("task_id", _P, True, lambda v: normalize_uuid(v, "task_id")),
            ("delegatee_username", _P, True, normalize_username),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "get_my_delegations": _spec(
        "get_my_delegations",
        (
            ("limit", int, False, _validate_limit),
            ("cursor", _P, False, None),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    # ------------------------------------------------------------------
    # Observers and gateway (SPEC.txt F18/F20)
    # ------------------------------------------------------------------
    "create_observer_account": _spec(
        "create_observer_account",
        (
            ("observer_name", _P, True, normalize_username),
            ("password", _P, True, validate_password),
            ("description", _P, True, normalize_description),
            ("organization_name_auth", _P, True, normalize_organization_name),
            ("organization_password_auth", _P, True, None),
        ),
        org=True,
    ),
    "revoke_observer_account": _spec(
        "revoke_observer_account",
        (
            ("observer_name", _P, True, normalize_username),
            ("organization_name_auth", _P, True, normalize_organization_name),
            ("organization_password_auth", _P, True, None),
        ),
        org=True,
    ),
    "list_observers": _spec(
        "list_observers",
        (
            ("organization_name_auth", _P, True, normalize_organization_name),
            ("organization_password_auth", _P, True, None),
        ),
        org=True,
    ),
    "get_org_snapshot": _spec(
        "get_org_snapshot",
        (
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    # ------------------------------------------------------------------
    # Human accounts and organization reading (SPEC-WEB)
    # ------------------------------------------------------------------
    "create_org": _spec(
        "create_org",
        (
            ("organization_name", _P, True, normalize_organization_name),
            ("organization_password", _P, True, validate_password),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "disable_org": _spec(
        "disable_org",
        (
            ("organization_name", _P, True, normalize_organization_name),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
        ),
    ),
    "list_org_conversations": _spec(
        "list_org_conversations",
        (
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
            ("limit", int, False, _validate_limit),
            ("cursor", _P, False, None),
        ),
    ),
    "get_org_conversation": _spec(
        "get_org_conversation",
        (
            ("conversation_id", _P, True, _validate_uuid_filter),
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
            ("limit", int, False, _validate_limit),
            ("cursor", _P, False, None),
        ),
    ),
    "change_agent_description": _spec(
        "change_agent_description",
        (
            ("username", _P, True, normalize_username),
            ("description", _P, True, normalize_description),
            ("organization_name_auth", _P, True, normalize_organization_name),
            ("organization_password_auth", _P, True, None),
        ),
        org=True,
    ),
    "list_orgs": _spec(
        "list_orgs",
        (
            ("my_name_auth", _P, True, None),
            ("my_password_auth", _P, True, None),
            ("include_disabled", bool, False, validate_bool),
        ),
    ),
}


def validate_envelope(request: Any) -> tuple[str, dict]:
    """Validates the complete envelope of a request.

    Returns ``(command, validated_parameters)``. Raises ``ApiError`` with
    ``UNKNOWN_COMMAND`` for an unknown command or ``INVALID_ARGUMENT``
    for any other format problem.

    The validated parameters contain the transformed values (normalized
    names, lowercase UUIDs, NFC/trimmed content, resolved limit).
    """
    if not isinstance(request, dict):
        raise _invalid("The request must be a JSON object")
    _ensure_exact_keys(request, ("api_version", "command", "parameters"), "envelope")

    api_version = request["api_version"]
    if not isinstance(api_version, str) or api_version != API_VERSION:
        raise _invalid(f"api_version must be '{API_VERSION}'")

    command = request["command"]
    if not isinstance(command, str):
        raise _invalid("command must be a string")
    if command not in COMMAND_SPECS:
        raise ApiError(UNKNOWN_COMMAND, f"Unknown command: {command}")

    parameters = request["parameters"]
    if not isinstance(parameters, dict):
        raise _invalid("parameters must be a JSON object")

    spec = COMMAND_SPECS[command]
    allowed = {param[0] for param in spec[1]}
    _ensure_exact_keys(parameters, tuple(sorted(allowed)), "parameters")

    validated: dict = {}
    for name, type_, required, validator in spec[1]:
        raw = parameters[name]
        if raw is None:
            if required:
                raise _invalid(f"The parameter '{name}' is required")
            # Validators of optional parameters accept None:
            # they apply the default value (e.g. limit -> 50) or
            # return None (status, sender_username, conversation_id...).
            if validator is not None:
                raw = validator(raw)
            validated[name] = raw
            continue
        if type(raw) is not type_:
            raise _invalid(f"The parameter '{name}' must be of type {type_.__name__}")
        if validator is not None:
            raw = validator(raw)
        validated[name] = raw
    return command, validated


def _ensure_exact_keys(mapping: dict, allowed: tuple[str, ...], label: str) -> None:
    """Refuses any unknown or missing field (exact keys)."""
    actual = set(mapping.keys())
    expected = set(allowed)
    unknown = actual - expected
    if unknown:
        raise _invalid(f"Unknown field in {label} : {sorted(unknown)[0]}")
    missing = expected - actual
    if missing:
        raise _invalid(f"Missing field in {label} : {sorted(missing)[0]}")


def parse_json_request(data: bytes) -> Any:
    """Strictly decodes a JSON request (strict UTF-8, no duplicate keys)."""
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise _invalid("Invalid JSON request (UTF-8)") from exc
    try:
        return json.loads(text, object_pairs_hook=_reject_duplicate_keys)
    except json.JSONDecodeError as exc:
        raise _invalid("Invalid JSON request") from exc
    except ValueError as exc:
        # duplicate keys (ValueError raised by object_pairs_hook)
        raise _invalid("Invalid JSON request") from exc
    except RecursionError as exc:
        # deeply nested JSON: malformed request, not an internal error
        raise _invalid("Invalid JSON request (excessive nesting)") from exc


def _reject_duplicate_keys(pairs: list) -> dict:
    result: dict = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"Duplicate key: {key}")
        result[key] = value
    return result
