"""Message-sending tests (section 6) and idempotency."""

from __future__ import annotations

import uuid

import pytest

from synapse.client import ApiClientError

from .conftest import ORG_NAME, ORG_PASSWORD, ALICE, ALICE_PASSWORD, BOB, BOB_PASSWORD

INVALID_ARGUMENT = "INVALID_ARGUMENT"
RECIPIENT_NOT_FOUND = "RECIPIENT_NOT_FOUND"
MESSAGE_ALREADY_EXISTS = "MESSAGE_ALREADY_EXISTS"
POLICY_DENIED = "POLICY_DENIED"


def test_send_message_full_shape(fx):
    sent = fx.send(ALICE, ALICE_PASSWORD, BOB, "Bonjour Bob", "cmid-shape-1")
    assert set(sent.keys()) == {
        "message_id",
        "conversation_id",
        "client_message_id",
        "sender_username",
        "sender_organization_name",
        "recipient_username",
        "content",
        "business_reference",
        "created_at",
        "status",
        "read_at",
    }
    assert sent["sender_username"] == ALICE
    assert sent["sender_organization_name"] == ORG_NAME
    assert sent["recipient_username"] == BOB
    assert sent["status"] == "unread"
    assert sent["read_at"] is None
    assert sent["business_reference"] is None
    uuid.UUID(sent["message_id"])
    uuid.UUID(sent["conversation_id"])
    assert uuid.UUID(sent["message_id"]).version == 4
    assert uuid.UUID(sent["conversation_id"]).version == 4
    assert sent["created_at"].endswith("Z")
    assert len(sent["created_at"]) == 24  # YYYY-MM-DDTHH:mm:ss.sssZ


def test_send_message_trim_and_nfc(fx):
    sent = fx.send(ALICE, ALICE_PASSWORD, BOB, "  \tBonjour\u00a0Bob  ", "cmid-trim-1")
    assert sent["content"] == "Bonjour\u00a0Bob"  # internal non-breaking spaces preserved
    sent2 = fx.send(ALICE, ALICE_PASSWORD, BOB, "e\u0301tude", "cmid-nfc-1")
    assert sent2["content"] == "\u00e9tude"


def test_send_message_unicode_content(fx):
    sent = fx.send(ALICE, ALICE_PASSWORD, BOB, "héllo 🌍 wörld", "cmid-uni-1")
    assert sent["content"] == "héllo 🌍 wörld"


def test_send_message_recipient_normalized(fx):
    sent = fx.send(ALICE, ALICE_PASSWORD, "BOB", "salut", "cmid-rec-1")
    assert sent["recipient_username"] == BOB


def test_send_to_self_rejected(fx):
    with pytest.raises(ApiClientError) as exc:
        fx.client.send_message(ALICE, "to myself", "cmid-self-1", ALICE, ALICE_PASSWORD)
    assert exc.value.code == INVALID_ARGUMENT


def test_send_to_unknown_recipient(fx):
    fx.client.set_organization_policy(True, True, ORG_NAME, ORG_PASSWORD)
    with pytest.raises(ApiClientError) as exc:
        fx.client.send_message("ghost", "salut", "cmid-ghost-1", ALICE, ALICE_PASSWORD)
    assert exc.value.code == RECIPIENT_NOT_FOUND


def test_send_to_disabled_recipient(fx):
    fx.client.set_organization_policy(True, True, ORG_NAME, ORG_PASSWORD)
    fx.client.deactivate_agent(BOB, ORG_NAME, ORG_PASSWORD)
    with pytest.raises(ApiClientError) as exc:
        fx.client.send_message(BOB, "salut", "cmid-dis-1", ALICE, ALICE_PASSWORD)
    assert exc.value.code == RECIPIENT_NOT_FOUND


def test_send_requires_active_sender(fx):
    fx.client.deactivate_agent(ALICE, ORG_NAME, ORG_PASSWORD)
    with pytest.raises(ApiClientError) as exc:
        fx.client.send_message(BOB, "salut", "cmid-act-1", ALICE, ALICE_PASSWORD)
    assert exc.value.code == "AUTH_FAILED"


def test_created_at_is_service_time_not_client_time(fx):
    """created_at is generated by the service (UTC), not by the caller."""
    import re
    sent = fx.send(ALICE, ALICE_PASSWORD, BOB, "horloge", "cmid-time-1")
    assert re.fullmatch(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z", sent["created_at"])


def test_send_message_max_content(fx):
    content = "é" * 10000
    sent = fx.send(ALICE, ALICE_PASSWORD, BOB, content, "cmid-max-1")
    assert len(sent["content"]) == 10000


def test_send_message_too_long(fx):
    with pytest.raises(ApiClientError) as exc:
        fx.client.send_message(BOB, "é" * 10001, "cmid-long-1", ALICE, ALICE_PASSWORD)
    assert exc.value.code == INVALID_ARGUMENT


def test_send_message_control_chars_rejected(fx):
    with pytest.raises(ApiClientError) as exc:
        fx.client.send_message(BOB, "ligne1\nligne2", "cmid-ctrl-1", ALICE, ALICE_PASSWORD)
    assert exc.value.code == INVALID_ARGUMENT


def test_send_creates_single_conversation(fx):
    m1 = fx.send(ALICE, ALICE_PASSWORD, BOB, "un", "cmid-c1")
    m2 = fx.send(BOB, BOB_PASSWORD, ALICE, "deux", "cmid-c2")
    m3 = fx.send(ALICE, ALICE_PASSWORD, BOB, "trois", "cmid-c3")
    assert m1["conversation_id"] == m2["conversation_id"] == m3["conversation_id"]


def test_send_conversation_key_independent_of_direction(fx):
    m1 = fx.send(ALICE, ALICE_PASSWORD, BOB, "un", "cmid-dir-1")
    m2 = fx.send(BOB, BOB_PASSWORD, ALICE, "deux", "cmid-dir-2")
    assert m1["conversation_id"] == m2["conversation_id"]


def test_separate_conversations_per_pair(fx):
    fx.client.create_agent("carol",  "motdepasse-carol-1", "Agent de test",  ORG_NAME, ORG_PASSWORD)
    m1 = fx.send(ALICE, ALICE_PASSWORD, BOB, "to bob", "cmid-pair-1")
    m2 = fx.send(ALICE, ALICE_PASSWORD, "carol", "to carol", "cmid-pair-2")
    assert m1["conversation_id"] != m2["conversation_id"]


# ---------------------------------------------------------------------------
# Idempotence
# ---------------------------------------------------------------------------


def test_idempotent_reuse_returns_same_message(fx):
    first = fx.send(ALICE, ALICE_PASSWORD, BOB, "Bonjour", "cmid-ido-1")
    second = fx.send(ALICE, ALICE_PASSWORD, BOB, "  Bonjour  ", "cmid-ido-1")
    assert first["message_id"] == second["message_id"]
    assert second["content"] == "Bonjour"


def test_idempotent_reuse_same_recipient_different_content(fx):
    fx.send(ALICE, ALICE_PASSWORD, BOB, "Bonjour", "cmid-ido-2")
    with pytest.raises(ApiClientError) as exc:
        fx.client.send_message(BOB, "autre chose", "cmid-ido-2", ALICE, ALICE_PASSWORD)
    assert exc.value.code == MESSAGE_ALREADY_EXISTS


def test_idempotent_reuse_different_recipient(fx):
    fx.client.create_agent("carol",  "motdepasse-carol-1", "Agent de test",  ORG_NAME, ORG_PASSWORD)
    fx.send(ALICE, ALICE_PASSWORD, BOB, "Bonjour", "cmid-ido-3")
    with pytest.raises(ApiClientError) as exc:
        fx.client.send_message("carol", "Bonjour", "cmid-ido-3", ALICE, ALICE_PASSWORD)
    assert exc.value.code == MESSAGE_ALREADY_EXISTS


def test_same_client_id_from_different_senders_allowed(fx):
    m1 = fx.send(ALICE, ALICE_PASSWORD, BOB, "de alice", "cmid-shared-1")
    m2 = fx.send(BOB, BOB_PASSWORD, ALICE, "de bob", "cmid-shared-1")
    assert m1["message_id"] != m2["message_id"]
    assert m1["client_message_id"] == m2["client_message_id"] == "cmid-shared-1"


def test_idempotent_reuse_after_read_returns_updated_state(fx):
    first = fx.send(ALICE, ALICE_PASSWORD, BOB, "Bonjour", "cmid-ido-4")
    fx.client.read_message(first["message_id"], BOB, BOB_PASSWORD)
    second = fx.send(ALICE, ALICE_PASSWORD, BOB, "Bonjour", "cmid-ido-4")
    assert second["message_id"] == first["message_id"]
    assert second["status"] == "read"  # current state, not the initial state


def test_idempotent_reuse_case_sensitive_client_id(fx):
    """client_message_id is compared exactly, character by character."""
    m1 = fx.send(ALICE, ALICE_PASSWORD, BOB, "Bonjour", "Cmid-1")
    m2 = fx.send(ALICE, ALICE_PASSWORD, BOB, "Bonjour", "cmid-1")
    assert m1["message_id"] != m2["message_id"]


def test_idempotent_reuse_case_sensitive_content(fx):
    """The normalized content is compared exactly: any difference (including
    case) with the same key triggers MESSAGE_ALREADY_EXISTS."""
    fx.send(ALICE, ALICE_PASSWORD, BOB, "Bonjour", "cmid-ido-5")
    with pytest.raises(ApiClientError) as exc:
        fx.client.send_message(BOB, "bonjour", "cmid-ido-5", ALICE, ALICE_PASSWORD)
    assert exc.value.code == MESSAGE_ALREADY_EXISTS


def test_idempotent_reuse_ignores_policy_change(fx):
    """SPEC.txt §6.1: the idempotent retrieval of an already-validated
    message is never affected by a communication-policy change."""
    from .conftest import ORG2_NAME, ORG2_PASSWORD, create_organization

    create_organization(fx.config, ORG2_NAME, ORG2_PASSWORD, ORG2_PASSWORD)
    fx.client.create_agent("dave", "motdepasse-dave-1", "Agent dave", ORG2_NAME, ORG2_PASSWORD)
    # open on both sides, then a validated send
    fx.client.set_organization_policy(True, True, ORG_NAME, ORG_PASSWORD)
    fx.client.set_organization_policy(True, True, ORG2_NAME, ORG2_PASSWORD)
    sent = fx.client.send_message(
        "dave", "already validated message", "cmid-policy-1", ALICE, ALICE_PASSWORD
    )
    # second_org's incoming policy closes again
    fx.client.set_organization_policy(False, True, ORG2_NAME, ORG2_PASSWORD)
    # strictly identical re-send: the already-validated message is returned
    again = fx.client.send_message(
        "dave", "already validated message", "cmid-policy-1", ALICE, ALICE_PASSWORD
    )
    assert again["message_id"] == sent["message_id"]
    # but a NEW message to dave is refused by the policy
    with pytest.raises(ApiClientError) as exc:
        fx.client.send_message("dave", "nouveau message", "cmid-policy-2", ALICE, ALICE_PASSWORD)
    assert exc.value.code == POLICY_DENIED
