# -*- coding: utf-8 -*-
"""Batch 2 : traduction FR->EN des fichiers CLI task/policy/backup/diag."""
import pathlib

M = {
# task.py
"# L'API utilise les états/priorités anglais ; le CLI accepte aussi les": "# The API uses English states/priorities; the CLI also accepts the",
"# équivalents français documentés par SPEC_CLI (traduction locale).": "# documented French equivalents (SPEC_CLI) — local translation.",
"filtrer par état (en_attente, en_cours, terminee…)": "filter by state (pending, in_progress, completed…)",
"filtrer par assigné": "filter by assignee",
"tâches d'un département (list_department_tasks)": "tasks of a department (list_department_tasks)",
"crée une tâche (créateur = compte authentifié)": "creates a task (creator = authenticated account)",
"assigné (requis)": "assignee (required)",
"normal, haute/basse (défaut : normal)": "normal, high/low (default: normal)",
"échéance (horodatage ISO)": "due date (ISO timestamp)",
"réservé : le créateur est le compte authentifié ": "reserved: the creator is the authenticated account ",
"(--my-name), pas un paramètre de l'API": "(--my-name), not an API parameter",
"réservé : create_task n'affecte pas de département": "reserved: create_task does not affect a department",
"détail d'une tâche": "details of a task",
"change l'état d'une tâche": "changes the state of a task",
"nouvel état (en_cours, terminee…)": "new state (in_progress, completed…)",
"résultat (pour terminee/failed)": "result (for completed/failed)",
"transfère une tâche": "transfers a task",
"nouvel assigné": "new assignee",
'["id", "titre", "état", "assigné"]': '["id", "title", "state", "assignee"]',
"--creator n'existe pas dans l'API : le créateur est le compte ": "--creator does not exist in the API: the creator is the account ",
"authentifié (identité via --my-name ou jeton local)": "authenticated (identity via --my-name or local token)",
"--department n'est pas supporté par create_task (les tâches d'un ": "--department is not supported by create_task (the tasks of a ",
"département se LISTENT avec 'synapse task list --department')": "department are LISTED with 'synapse task list --department')",
"Tâche créée : ": "Task created: ",
"(état ": "(state ",
"Tâche {args.task_id} : état ": "Task {args.task_id}: state ",
"approuvée.": "approved.",
"refusée.": "rejected.",
"Approbation demandée pour ": "Approval requested for ",
"transférée à ": "transferred to ",
'["id", "titre", "état", "échéance"]': '["id", "title", "state", "due"]',
# policy.py
"Groupe ``policy`` (SPEC_CLI §4.9) : politiques, escalade, délégations.": "``policy`` group (SPEC_CLI §4.9): policies, escalation, delegations.",
"Écarts API documentés (docs/SPEC_CLI_ECARTS.md) :": "Documented API deviations (docs/SPEC_CLI_ECARTS.md):",
"* ``delegate`` : l'API ``create_delegation`` délègue une TÂCHE à un agent": "* ``delegate``: the ``create_delegation`` API delegates a TASK to an agent",
'  avec une échéance (pas des « capacités ») — la commande prend donc': '  with a due date (not "capabilities") — the command therefore takes',
"* ``revoke`` : l'API révoque par (tâche, délégataire) — ``revoke <agent>": "* ``revoke``: the API revokes by (task, delegatee) — ``revoke <agent>",
"politique d'escalade (lecture) ; --set pour écrire": "escalation policy (read); --set to write",
"écriture de la politique": "write the policy",
"seuil de retard en heures (délai d'échéance)": "late threshold in hours (due delay)",
"supportées par l'API)": "supported by the API)",
"délègue une tâche à un agent (create_delegation)": "delegates a task to an agent (create_delegation)",
"agent délégataire": "delegatee agent",
"identifiant de la tâche déléguée": "identifier of the delegated task",
"échéance de la délégation (horodatage ISO, requis)": "delegation due date (ISO timestamp, required)",
"révoque une délégation (revoke_delegation)": "revokes a delegation (revoke_delegation)",
"délégations reçues par l'agent courant": "delegations received by the current agent",
"'autorisé' if incoming else 'refusé'": "'allowed' if incoming else 'denied'",
"'autorisé' if outgoing else 'refusé'": "'allowed' if outgoing else 'denied'",
"# Écriture : valeurs par défaut = politique courante (lecture d'abord).": "# Write: defaults = current policy (read first).",
"Politique d'escalade de '{args.org}' mise à jour ": "Escalation policy of '{args.org}' updated ",
"Tâche {args.task} déléguée à {args.agent} ": "Task {args.task} delegated to {args.agent} ",
"(échéance {args.expires}).": "(due {args.expires}).",
"Délégation de la tâche {args.task} à {args.agent} révoquée.": "Delegation of task {args.task} to {args.agent} revoked.",
'["délégateur", "tâche", "échéance"]': '["delegator", "task", "due"]',
# backup.py
"Groupe ``backup`` (SPEC_CLI §4.12) : sauvegardes chiffrées.": "``backup`` group (SPEC_CLI §4.12): encrypted backups.",
"rétention : 14 archives maximum": "retention: at most 14 archives",
"sauvegarde complète (base SQLite + clés)": "full backup (SQLite database + keys)",
"répertoire de sortie (défaut : backup_dir de la config)": "output directory (default: backup_dir from config)",
"chemin de fichier exact (compatibilité synapse-backup)": "exact file path (synapse-backup compatibility)",
"restauration depuis une archive (serveur arrêté)": "restore from an archive (server stopped)",
"confirme la destruction des données actuelles": "confirms the destruction of current data",
"rétention : supprime les archives au-delà de --keep": "retention: deletes archives beyond --keep",
"nombre d'archives à conserver (défaut : 14)": "number of archives to keep (default: 14)",
"répertoire des archives (défaut : backup_dir de la config)": "archives directory (default: backup_dir from config)",
"preuve de restauration : vérifie une archive ": "restore proof: verifies an archive ",
"dans un stockage isolé, sans toucher la production": "in isolated storage, without touching production",
"vérifier l'archive la plus récente du backup_dir": "verify the most recent archive of backup_dir",
"répertoire de travail (scratch) ; créé temporairement ": "working (scratch) directory; created temporarily ",
"par défaut ; ne doit pas contenir le stockage de production": "by default; must not contain production storage",
"# backup() écrit dans le répertoire avec un nom horodaté": "# backup() writes into the directory with a timestamped name",
"Sauvegarde chiffrée (AES-256-GCM) terminée.": "Encrypted backup (AES-256-GCM) complete.",
"opération destructrice — passez --force pour confirmer ": "destructive operation — pass --force to confirm ",
"(les données actuelles seront remplacées)": "(current data will be replaced)",
"Restauration terminée.": "Restore complete.",
'["archive", "taille", "créée le", "format"]': '["archive", "size", "created", "format"]',
"rétention respectée : au plus ": "retention respected: at most ",
"supprimée(s) (rétention : ": "deleted (retention: ",
"  créée le    ": "  created     ",
"  intégrité   ": "  integrity   ",
"Restauration prouvée dans un stockage isolé ; production intacte.": "Restore proven in isolated storage; production untouched.",
"En-tête déchiffré d'une archive (format + date de création).": "Decrypted header of an archive (format + creation date).",
# diag.py
"Groupe ``diag`` (SPEC_CLI §4.15) : état détaillé et diagnostic.": "``diag`` group (SPEC_CLI §4.15): detailed state and diagnostics.",
"état global détaillé": "detailed global state",
"diagnostic d'environnement (7 contrôles)": "environment diagnostics (7 checks)",
"diagnostic (status détaillé, doctor)": "diagnostics (detailed status, doctor)",
"  jeton web ": "  web token ",
"  requêtes  ": "  requests  ",
"État du web : PID vivant ET HTTP répond (pas de socket Unix).": "Web state: live PID AND HTTP responds (no Unix socket).",
"en cours d'exécution": "running",
"arrêté": "stopped",
"# diag doctor — 7 contrôles (SPEC_CLI §4.15)": "# diag doctor — 7 checks (SPEC_CLI §4.15)",
'["verdict", "contrôle", "détail"]': '["verdict", "check", "detail"]',
" contrôle(s) en échec — corrigez avant de démarrer.": " check(s) failing — fix before starting.",
"Diagnostic complet : aucun contrôle en échec.": "Diagnostic complete: no failing checks.",
"n'est pas un répertoire": "is not a directory",
"# créé à la première sauvegarde": "# created at the first backup",
"répertoires": "directories",
"ATTENTION": "WARNING",
"stockage, run, logs et backups présents et en 0700": "storage, run, logs and backups present with 0700 permissions",
"absent (serveur arrêté ?)": "absent (server stopped?)",
"présent et répondant": "present and responding",
"présent mais ne répond pas": "present but not responding",
"ÉCHEC": "FAIL",
}

keys = sorted(M, key=len, reverse=True)
for f in ["synapse/cli/task.py", "synapse/cli/policy.py", "synapse/cli/backup.py", "synapse/cli/diag.py"]:
    p = pathlib.Path(f)
    t = p.read_text(encoding="utf-8")
    n = 0
    for k in keys:
        c = t.count(k)
        if c:
            t = t.replace(k, M[k])
            n += c
    p.write_text(t, encoding="utf-8")
    print(f"{f}: {n}")
